language: r
cache: packages
sudo: true
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - sa.ra.online@posteo.de
    on_success: always # default: change
    on_failure: always # default: always
