language: r
cache: packages
sudo: true
warnings_are_errors: false

addons:
  apt:
    packages:
      - gcc-4.8-base
      - libgfortran4
      - gcc-fortran

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 60

r:
  - oldrel
  - release
#  - devel

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - sa.ra.online@posteo.de
    on_success: change # default: change
    on_failure: always
