language: r
cache: packages
sudo: true
warnings_are_errors: false

addons:
  apt:
    packages:
      - gcc-4.4
      - g++-4.4
      - clang

r:
  - oldrel
  - release
#  - devel

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - sa.ra.online@posteo.de
    on_success: change # default: change
    on_failure: change # default: always
